services:
  mlflow:
    build:
      context: .
      dockerfile: infra/Dockerfile.mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_local:/app/mlflow_local

  api:
    build:
      context: .
      dockerfile: infra/Dockerfile.fastapi
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - TEN_MODEL_IQA=iqa_viet_hoa
      - ALIAS_IQA=thu_nghiem
    ports:
      - "8000:8000"
    depends_on:
      - mlflow