name: CD Local (Windows)

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: [self-hosted, windows-iqa]

    steps:
      - uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        shell: powershell
        working-directory: Project_CK
        run: |
          docker compose down
          docker compose up -d --build
          docker compose ps
